# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and rarely edit after that. If you find yourself editing this file very often, consider using Jekyll's data files feature for the data you need to update frequently.

# Site settings
title:            Lorem Ipsum
email:            example@example.com
description:      Lorem ipsum dolor sit amet...
baseurl:          /nycdh-jekyll # ''
url:              ''

twitter_username: example
github_username:  example

# Build settings
markdown:         kramdown
remote_theme:     broccolini/athena
permalink:        pretty
exclude:          [Gemfile*, vendor]
plugins:          [jekyll-feed, jekyll-remote-theme]
